### ISSUE TITLE
Request timeout | Server broke connection

### ISSUE THREAD

**Issue by vladi-dev** [apiaryio/apiary-client#124]
I'm having trouble with publishing my docs. 
After executing this command
`APIARY_API_KEY="mykey" apiary publish --path=API_DOCS.md --api-name='mydomain'`
I get one of this errors
`Apiary service responded with an error: Request Timeout`
or
`Apiary service responded with an error: Server broke connection`

The internet connection is good, I tried execute the command many times during the day so I don't think that apiary server is down.

My file is large ~ 2.5 Mb. Could it be the reason? If yes how can I solve this?

**Comment by raymondkpwong** [comment]
We have something very similar here.  When we publish a file of about 3.6M, the server responds "Server broke connection".  Actually, the response is, 

```sh
$ apiary publish --api-name="myapi"
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize': no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/apiaryio-0.4.2/lib/apiary/command/publish.rb:77:in `rescue in query_apiary'
	from /Library/Ruby/Gems/2.0.0/gems/apiaryio-0.4.2/lib/apiary/command/publish.rb:67:in `query_apiary'
	from /Library/Ruby/Gems/2.0.0/gems/apiaryio-0.4.2/lib/apiary/command/publish.rb:52:in `publish_on_apiary'
	from /Library/Ruby/Gems/2.0.0/gems/apiaryio-0.4.2/lib/apiary/command/publish.rb:40:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/apiaryio-0.4.2/lib/apiary/cli.rb:42:in `publish'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/apiaryio-0.4.2/bin/apiary:5:in `<top (required)>'
	from /usr/local/bin/apiary:23:in `load'
	from /usr/local/bin/apiary:23:in `<main>'
```

We added a line to print the exception in publish.rb and it actually threw `Server broke connection`.  We copied the same apiary.apib to the web console and save it.  The web console works perfectly so it looks like the API does not accept large file.  Is there anyway to get around this?  This becomes quite annoying now.

**Comment by emve-dev** [comment]
@raymondkpwong i solved this by cutting the file size. Turns out i had a few json schemas included that were 50k lines long, not readable anyway, so I removed them. 
Would be great to get some response from apiary though.

**Comment by raymondkpwong** [comment]
I started to break the apib file into smaller one and set up multiple APIs in apiary.io to manage them.  It looks fine to work in this way but it defeats the purpose of adopting apiary.

I think this file size problem is a design flaw more than a technical problem.  apiary.io provides dredd for testing and CI.  In order to achieve this, all APIs should be consolidated into one place (I doubt this is available).  And sometimes we put test data in apib for edge case testing.  So, it is very likely that we'll get a very big apib.  But, apiary avoids accepting files larger than 2 MB like setting up a wall for security purpose.  

We shall wait and see whether apiary can improve this.

**Comment by emve-dev** [comment]
Agree, it makes no sense to restrict uploading files over 2Mb when one can upload same file using web editor 👍

**Comment by abtris** [comment]
Here is limitation 30s for heroku for request timeout. Apiary have to get document and parse them before save. Save is done only for valid documents. Try use [MSON](https://help.apiary.io/api_101/mson-tutorial/) to make document smaller.

**Comment by JackuB** [comment]
We also have few other suggestions on working with documents larger than 1 MB on Apiary Help - https://help.apiary.io/faq/file-size/#how-to-deal-with-big-api-description-documents

@raymondkpwong For Dredd testing, you can always add bigger/edge payloads through [Dredd hooks](https://dredd.readthedocs.io/en/latest/hooks/) to keep your APIB clean.
