### ISSUE TITLE
Feature request: Live preview with hot-reload

### ISSUE THREAD

**Issue by jsynowiec** [apiaryio/apiary-client#128]
Is there a hidden configuration file that wasn't mentioned in the documentation? Currently live-reload is not working for me and I'm not sure where I should change those Babel settings.

<img width="1476" alt="apiary-console" src="https://cloud.githubusercontent.com/assets/1029142/17103598/68709262-527f-11e6-9727-c7d357603b23.png">

I'm starting the preview server using `apiary preview --path="src/api.apib" --server --port 8080`

**Comment by JackuB** [comment]
@jsynowiec hey, currently, auto-reload is not in CLI. These warnings are unrelated to Apiary CLI, as they are originating in our frontend documentation and are referring to a development of our react modules. Documentation team knows about them and should resolve them soon. 

Nevertheless, I really like the idea of having live-reload. You change `.apib/.yaml` and preview page reloads. I'm adding it to our pipeline.

**Comment by jsynowiec** [comment]
@JackuB Thanks for clarification. I'm looking forward for this feature. If you are using React for rendering maybe some sort of hot reloading just the modified parts would be possible?

**Comment by jsynowiec** [comment]
@JackuB any news about this enhancement. Live-preview with hot-reloading would greatly improve overall experience when documenting an API.

**Comment by JackuB** [comment]
@jsynowiec hey, just found this in my email, sorry, was swamped with other work. Documentation is not a single React app, thus hot reload won't be possible anytime soon afaik. This feature is in our backlog, not exactly high nor low, so no ETA now, but we'll get to it.

**Comment by jsynowiec** [comment]
@XVincentX does it means that live-reload will be available in next release or was dropped from backlog?

**Comment by JackuB** [comment]
Maybe @XVincentX implemented it? :)
I'll look into it today

**Comment by XVincentX** [comment]
I think I mis-clicked the buttons.

**Comment by tu1ly** [comment]
https://github.com/apiaryio/apiary-client/pull/142
