### ISSUE TITLE
NoMethodError: undefined method `Publish' for Apiary::Command:Module

### ISSUE THREAD

**Issue by mifkamaz** [apiaryio/apiary-client#131]
I want to use this gem for validation api from RSpec

```
class Test
  def self.test
    publish = Apiary::Command::Publish(
        {
            "api_key"=>"24596aa4c2e6513e4ff51f2bee6e440d",
            "api_name"=>"test9905",
            "path"=>"make_events_client_v2.apib",
        }
    )
    publish.execute
  end
end
```
And when I run command in rails console:  ```Test.test```
Give error: ```NoMethodError: undefined method `Publish' for Apiary::Command:Module```

How to solve this problem?

**Comment by tu1ly** [comment]
@mifkamaz `Publish` is class not a method
https://github.com/apiaryio/apiary-client/blob/master/lib/apiary/command/publish.rb#L12

you want to call `execute` on `Publish` instance
https://github.com/apiaryio/apiary-client/blob/master/lib/apiary/command/publish.rb#L39

`Apiary::Command::Publish.new(options).execute()`
