### ISSUE TITLE
Feature Request: Return Semantic Validation Warnings on Publish

### ISSUE THREAD

**Issue by ralphcallaway** [apiaryio/apiary-client#134]
It would be a productivity boon if the apiary client could print a list of semantic validation issues with line numbers to stderr during the publish command. My current workflow is (1) make changes locally, (2) run a build script, (3) open it up in apiary and check if there are any validation errors

I could skip step 3 if the errors were somehow returned by the client.

**Comment by kylef** [comment]
@ralphcallaway There are a large number of editor plugins for API Blueprint (https://apiblueprint.org/tools.html) which can offer you validations right from your editor. You might want to check these out. You can also use the [drafter](https://github.com/apiaryio/drafter) command line tool for local validation of an API Blueprint.

If you're using Swagger, you should be able to find a similar plugin if you search for swagger and your editor.

---

Printing out the warnings and errors when you attempt to publish would be a great addition to the apiary client. I think it might be difficult to implement at the moment considering all of the parser adapters are in node.js and this client is in Ruby.

**Comment by ralphcallaway** [comment]
I'm using the ST3 plugin, not much there functionality wise yet.

Will check out drafter, sounds like we could add that to our build script

**Comment by kylef** [comment]
Providing you install the Drafter command line tool. The API Blueprint Submline plugin (https://github.com/apiaryio/api-blueprint-sublime-plugin) will start using this to provide live validations.

**Comment by ralphcallaway** [comment]
Derp, had no idea there were installation requirements for the plugin to work, thanks for the tip!
