### ISSUE TITLE
It's not possible to publish a JSON Swagger document

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/apiary-client#137]
Let's say I have an `example.json` file, which contains a Swagger API description document serialized as JSON. Then following command:

```
$ APIARY_API_KEY=... apiary publish --api-name=demouser --path=./example.json
```

Results in following output:

```
Apiary service responded with an error: Internal Error.
```

**Comment by JackuB** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apiary CLI should support JSON files (?)](https://trello.com/c/ww18aXRz/194-apiary-cli-should-support-json-files)

**Comment by tu1ly** [comment]
it is caused by parser in apiary core app - it accepts yaml only

**Comment by tu1ly** [comment]
@honzajavorek workaround is to convert to yaml before publishing

**Comment by honzajavorek** [comment]
Yes, the workaround is pretty obvious, but from user perspective, it's
inconsistent experience, because you can input JSON in the editor, but you
can't using the API / apiary client.

**Comment by kylef** [comment]
This is strange, because JSON is actually a superset of YAML. A JSON document is also a valid YAML document.

---

> @honzajavorek workaround is to convert to yaml before publishing

I'd advise against this solution, since the source maps for any warnings or errors will become wrong since they will be against different source.
