### ISSUE TITLE
Ruby DependencyError for public_suffix

### ISSUE THREAD

**Issue by jromero** [apiaryio/apiary-client#139]
```bash
sudo gem install apiaryio
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: apiaryio requires public_suffix (~> 1.4.6); addressable requires public_suffix (>= 2.0.2, ~> 2.0)

```

Looking at https://rubygems.org/gems/apiaryio/versions/0.6.0 it seems like a new dependency for `public_suffix ~> 1.4.6` was added while `launchy ~> 2.4` -> `addressable ~> 2.3 ` depends on `public_suffix >= 2.0.2, ~> 2.0`

**Comment by tu1ly** [comment]
@jromero thx! - fixed in https://github.com/apiaryio/apiary-client/releases/tag/v0.6.1
