### ISSUE TITLE
How to get `--watch` working?

### ISSUE THREAD

**Issue by cloud171** [apiaryio/apiary-client#144]
Can't seem to get the `--watch` feature to work and I've tried the following on macOS 10.12 using `0.7.0` with Firefox:

* `apiary preview --watch` and opens a  new browser tab and nothing happens when I save changes to the original file
* `apiary preview --server --watch` and endlessly complains about the following with different directories

       ** ERROR: directory is already being watched! **

        Directory: /Users/cloud_171/Library/Containers/com.apple.iPhoto/Data/Desktop

        is already begin watched through: /Users/cloud_171/Desktop

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors

**Comment by tu1ly** [comment]
* --server is needed for the `watch` functionality as the output needs to be served dynamically - i'll mention it in readme/help
* it is a limitation of the 'listen' lib used for detecting ADD changes - we'll try to solve it in near future

**Comment by cloud171** [comment]
@tu1ly Thanks! Should've actually read the duplicate directory error link and the workaround would be obvious.

**Comment by danilokleber** [comment]
I've come across this error but it seems that the wiki for the duplicate directory error is nowhere to be found. Could you point me to another resource? Thanks!
