### ISSUE TITLE
v0.0.6, v0.0.7 and v0.0.8 not on rubygems

### ISSUE THREAD

**Issue by Dorian** [apiaryio/apiary-client#149]
Hi, it's here in the GitHub repo but not on rubygems ;)

https://rubygems.org/gems/apiary

<img width="406" alt="screen shot 2017-03-28 at 11 21 01" src="https://cloud.githubusercontent.com/assets/129149/24420737/a44289ea-13a8-11e7-90f6-4f02d07f4806.png">

**Comment by tu1ly** [comment]
hi @Dorian  , you are looking at different gem :) - this is ours https://rubygems.org/gems/apiaryio

**Comment by Dorian** [comment]
Thanks, having three names makes it a bit confusing. Apiary, apiary-client and apiary (and honey, just kidding)
