### ISSUE TITLE
Publishing JSON Api broken on Windows: undefined method `to_yaml'

### ISSUE THREAD

**Issue by lukeryannetnz** [apiaryio/apiary-client#152]
Hello Apiary team

Publishing JSON from windows doesn't work. 
I have the following version of ruby on Windows 10:  ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]

Could this be a version specific issue? Which gem goes the to_yaml method come from? Json?

PS >apiary publish --api-name=[NAME] --path "ServiceContract.json" --json
C:/Ruby22/lib/ruby/gems/2.2.0/gems/apiaryio-0.8.0/lib/apiary/helpers.rb:21:in `convert_from_json': undefined method `to_yaml' for #<Hash:0x51cbe20> (NoMethodError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/apiaryio-0.8.0/lib/apiary/command/publish.rb:67:in `query_apiary'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/apiaryio-0.8.0/lib/apiary/command/publish.rb:53:in `publish_on_apiary'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/apiaryio-0.8.0/lib/apiary/command/publish.rb:41:in `execute'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/apiaryio-0.8.0/lib/apiary/cli.rb:45:in `publish'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/apiaryio-0.8.0/bin/apiary:5:in `<top (required)>'
        from C:/Ruby22/bin/apiary:23:in `load'
        from C:/Ruby22/bin/apiary:23:in `<main>'

**Comment by tu1ly** [comment]
hi,

thx for the report. I'll take a look on it 
 Yes `to_yaml` come from json

**Comment by tu1ly** [comment]
https://github.com/apiaryio/apiary-client/pull/154
