### ISSUE TITLE
preview should be entirely static -  no live dependency on apiary

### ISSUE THREAD

**Issue by balupton** [apiaryio/apiary-client#155]
My impression of the `apiary preview` command was that it generated a HTML file that was my rendered documentation...

I looked at the source code of the generated file today, and discovered that is not true. All it does is wraps the APIB file inline to the HTML and forwards it on to apiary. This was surprising, and probably means the company I am consulting for will need to switch away from apiary's documentation to another documentation generator that is entirely static.

**Comment by JackuB** [comment]
@balupton what would you expect from such static docs?

**Comment by balupton** [comment]
the same thing that is rendered, but it hits the host directly - we have no need for the CORS stuff, as can just host the docs on the server that we are doing the docs for

**Comment by JackuB** [comment]
Just wanted to give you an update: this is planned rather soon - there is a new static Apiary documentation renderer and it will be part of the Apiary CLI.

**Comment by mgwelch** [comment]
> what would you expect from such static docs?

At a minimum I'd expect the generated links to be correct. Hover over any navigation link and you can see that they go to jsapi.apiary.io. Due to javascript (I guess) the links work as expected. Unless you right click on one and bookmark it, or copy it. Then you get a link to jsapi.apiary.io. 

<img width="590" alt="image" src="https://user-images.githubusercontent.com/824136/57388488-e9456280-717d-11e9-8ef4-e96a8f053adc.png">

**Comment by mgwelch** [comment]
I'm going off on a tangent here: 

I currently use Apiary (the product), but dealing with Oracle for billing and service is a nightmare. They still don't have my billing correct. They are charging me for usage while the published quotes are clearly $30/user/month. When I contacted them they quoted me a line from page 67 of the service agreement that was in no way clearly documented to be part of the service I bought. Could you imagine if the entire collection of web offerings worked like that? Quoting page 67 of the service agreement.

**Comment by Almad** [comment]
@mgwelch 

> I'm going off on a tangent here

I am sorry for that and we do try to make things, well, smoother. 

That said, I wonder what they are charging you since yes, it should be $30/month, but _pro rated_, so they should only charge you less than this amount. 

That said, better channel for this is support@apiary.io, hard to discuss particular data on github...

**Comment by mgwelch** [comment]
> That said, I wonder what they are charging you since yes, it should be $30/month, but _pro rated_, so they should only charge you less than this amount.

They are charging me for usage (which right now is lower than $30/month). Here's the quote I got from someone:

> As per the Service Description document, page 68, the service fee for Apiary is calculated on an hourly basis as follows: 1/744 multiplied by the total number of hours incurred by your maximum configured users multiplied by the Pay as You Go which pretty much means that the fixed charge of 30$ /user/month does not apply...

You'll notice that the published pricing for Apiary doesn't have a Service Description document link. It's the Oracle API Platform Cloud Service that has a link to a Service Description.

**Comment by mgwelch** [comment]
> That said, better channel for this is [support@apiary.io](mailto:support@apiary.io), hard to discuss particular data on github...

Sorry I just saw this after posting. The last time I tried support at apiary I was promptly routed to Oracle. The first time I ever called Oracle they said "We don't have a product called Apiary". Eventually someone was willing to listen to me and admit that ok perhaps we do have a product called Apiary. Took quite a bit of emails to get to that point.

I just learned yesterday that the rep I had been working with is no longer at Oracle. He was very responsive, even if he was limited in what he could do.

**Comment by Almad** [comment]
> They are charging me for usage (which right now is lower than $30/month). 

If 1 user is using the service for full month, it should be $30. 

> You'll notice that the published pricing for Apiary doesn't have a Service Description document link. It's the Oracle API Platform Cloud Service that has a link to a Service Description.

Apiary is technically part of Oracle API Platform Cloud Service product, but we are selling it separately and it should not bubble up except for some documents like this one. 

> The last time I tried support at apiary I was promptly routed to Oracle.

:( The support is manned by our engineering team, but it is true they don't have access to all billing details, which unfortunately only the main support channel has. 

It is true that if the main problem is billing details, that's unfortunately on the Oracle's cloud portal support which should be reachable from the main console, I don't have access there either :S

**Comment by abtris** [comment]
Apiary client shouldn't provide static version. For API blueprint we can just recommend use some others tools https://apiblueprint.org/tools.html#renderers
