### ISSUE TITLE
Using it on a rails 5 project

### ISSUE THREAD

**Issue by chischaschos** [apiaryio/apiary-client#156]
Hi, is there a specific reason why rack is defined as?:

```ruby
gem.add_runtime_dependency 'rack', '~> 1.6.4'
```

I'm getting this error when trying to use it on a rails 5 project:

```bash
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 5.1.1) was resolved to 5.1.1, which depends on
      actionpack (= 5.1.1) was resolved to 5.1.1, which depends on
        rack (~> 2.0)

    apiaryio (~> 0.3.3) was resolved to 0.3.3, which depends on
      rack (~> 1.6.4)
```

Thank you in advance

**Comment by tu1ly** [comment]
i'll try to update it - imho it is not needed anymore (as we've dropped support for ruby < 2.0)

**Comment by chischaschos** [comment]
Right, thank you

**Comment by chischaschos** [comment]
Also I just realized that the approach where a rake task invoked with `bundle exec` doing a:

```ruby
  `apiary publish --path=docs/api/v1/apispec.md --api-name=fitforme`
```

Does not work. I would get this error:

```
/Users/chischaschos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/rubygems_integration.rb:377:in `block (2 levels) in replace_gem': apiaryio is not part of the bundle. Add it to your Gemfile. (Gem::LoadError)
        from /Users/chischaschos/.rbenv/versions/2.3.1/bin/apiary:22:in `<main>'
```

Checking the bundler documentation I just learned that:

> It also modifies Rubygems, disallow loading additional gems not in the bundle

Well, just sharing my findings 😃

**Comment by tu1ly** [comment]
https://github.com/apiaryio/apiary-client/pull/164
