### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by abhinavmsra** [apiaryio/apiary-client#157]
I installed the gem and exported the API Tokens. But when i try to run `apiary`, I get following error:

```
`help` is not an apiary command.
/ruby-2.3.1/gems/apiaryio-0.0.1/lib/apiary/cmd.rb:54:in `rescue in run': uninitialized constant Apiary::Command::OptionParser (NameError)
        from /Users/abhinav/.rvm/gems/ruby-2.3.1/gems/apiaryio-0.0.1/lib/apiary/cmd.rb:50:in `run'
        from /Users/abhinav/.rvm/gems/ruby-2.3.1/gems/apiaryio-0.0.1/lib/apiary/cli.rb:9:in `start'
        from /Users/abhinav/.rvm/gems/ruby-2.3.1/gems/apiaryio-0.0.1/bin/apiary:11:in `<top (required)>'
        from /Users/abhinav/.rvm/gems/ruby-2.3.1/bin/apiary:23:in `load'
        from /Users/abhinav/.rvm/gems/ruby-2.3.1/bin/apiary:23:in `<main>'
        from /Users/abhinav/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/abhinav/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

I am not sure whether its a installation error or a CLI error

**Comment by JackuB** [comment]
Is that `apiaryio-0.0.1` version? The `cmd.rb` is not part of this repo for years. Could you try checking your gemfile.lock for an `apiaryio` version?

**Comment by abhinavmsra** [comment]
@JackuB let me outline the steps:

1. Added `gem 'apiaryio'` to the Gemfile. In Gemfile.lock the version is indeed 0.0.1.

2. Exported the api key using `export APIARY_API_KEY="<token>"`

3. Tried running the CLI. `apiary fetch --api-name="<API_NAME>"`
I still get the same error.

**Comment by JackuB** [comment]
@abhinavmsra current version on rubygems is 0.8.1 https://rubygems.org/gems/apiaryio - update the gemfile to the latest version
