### ISSUE TITLE
Preview with --api-host doesn't reflect in the docs

### ISSUE THREAD

**Issue by bhenderson** [apiaryio/apiary-client#161]
When I use `apiary preview --api-host=my.host.dev` all the generated URLs still contain `example.tld`

Am I doing something wrong?

thanks,

**Comment by tu1ly** [comment]
`api-host` is host of apiary  API which is called by client (it has no  sense for preview command), it is used  for debugging purposes during the development only. imho we should remove it from the documentation

**Comment by bhenderson** [comment]
I see, is there a way to change the HOST value from the command line? I want to set it to me.dev for the preview server command for testing the apis locally.

**Comment by tu1ly** [comment]
`is there a way to change the HOST value from the command line` - unfortunately no - but feel free to submit a pull request :)

**Comment by bhenderson** [comment]
@tu1ly where would I start to look? 'example.tld' isn't in the client repo.

thanks,
