### ISSUE TITLE
Watch does not work properly

### ISSUE THREAD

**Issue by fgblomqvist** [apiaryio/apiary-client#168]
![screenshot from 2018-04-10 17-03-52](https://user-images.githubusercontent.com/649260/38589675-4bc0b9fa-3ce1-11e8-81c2-9dd563467e62.png)
Using latest Chrome and latest apiaryio.
It opens in my browser as `file:///tmp/apiary-preview.html`

EDIT:
When I said latest apiaryio I meant latest from gem install (0.10.2). The release tags here seem to be out of sync with rubygems.org. I'm gonna try master to see if the problem is still there.

**Comment by tu1ly** [comment]
you need to open page served on http://localhost:8080/

**Comment by fgblomqvist** [comment]
@tu1ly Nope, nothing is served on that address.
I launch it with `apiary preview --watch` and the only output I get is `Created new window in existing browser session.`. It's still running but there is no further output.

Checked the help and added the `--server` option (shouldn't this be automatic if you specify --watch? Or what purpose does watch have if you don't specify --server?). Now it's serving on localhost, however, the refresh is still not working:
![screenshot from 2018-04-12 10-14-25](https://user-images.githubusercontent.com/649260/38692968-54536c84-3e3a-11e8-87ba-7280c89bac4c.png)

**Comment by fgblomqvist** [comment]
Seems like this was partially fixed in #167 just not released yet. `--server` should imo still be set automatically if `--watch` is set.

**Comment by tu1ly** [comment]
you are right  `--watch` does not make sense without `--server`. we'll change it (or feel free to submit PR :) ) 

https://github.com/apiaryio/apiary-client/pull/167 will be released in next release - next week

**Comment by fgblomqvist** [comment]
Submitted a PR (I'll happily accept feedback since neither my insight into this project nor my ruby skills are perfect). Tested it out and it works like expected now :smiley:

**Comment by tu1ly** [comment]
fixed https://github.com/apiaryio/apiary-client/pull/169
