### ISSUE TITLE
Browser console not working with "--server --preview" option

### ISSUE THREAD

**Issue by ggicci** [apiaryio/apiary-client#175]
Hi, I started a server at localhost by using command:

```bash
apiary preview --server --port=9000 --watch --path="./api-description.apib" &>/dev/null
```

but I can't switch to console. If I click the button `Switch to Console`, it will print errors in the console:

```
> Uncaught TypeError: Cannot read property '_id' of undefined
    at a.initialize (docs-5c21b62e.js:1)
    at a.c (docs-5c21b62e.js:1)
    at a (docs-5c21b62e.js:1)
    at new a (docs-5c21b62e.js:1)
    at a.renderErrorView (docs-5c21b62e.js:1)
    at a.render (docs-5c21b62e.js:1)
    at a.renderConsoleView (docs-5c21b62e.js:1)
    at a.render (docs-5c21b62e.js:1)
    at a.initConsoleView (docs-5c21b62e.js:1)
    at a.renderConsoleView (docs-5c21b62e.js:1)

> GET chrome-extension://invalid/ net::ERR_FAILED
```
And my apiary cli version is **0.11.1**.

**Comment by tu1ly** [comment]
@ggicci thanks for the report. we'll take look at it. does it anyhow affecting functionality ?

**Comment by tu1ly** [comment]
@ggicci thanks for the report.
could you pls send me `api-description.apib` and info about browser you are using ?

**Comment by ggicci** [comment]
Hi, is there any progress?

**Comment by tu1ly** [comment]
hi, unfortunately no

**Comment by zloyboldin** [comment]
I have the same problem
BUT! Everything is fine on Firefox

**Comment by cyberbudy** [comment]
I have an error in my console on Firefox 68
this.applicationModel.get(...).get(...)

**Comment by abtris** [comment]
Try in latest version if issue still valid.
