### ISSUE TITLE
Disable browser console not working when using preview option

### ISSUE THREAD

**Issue by devatleadiq** [apiaryio/apiary-client#177]
How can I disable browser console view? We are following https://github.com/pipefy/doc-api-general to document our GraphQL. But we don't want the console view showing up. How can we turn it off at the generated HTML?

**Comment by tu1ly** [comment]
hi, `apiary preview` is meant to be used as development/debuging tool not to generate public facing documentation - it has limited functionality. better option is to save your documentation to https://apiary.io/ and follow https://help.apiary.io/tools/embed/#apiary-embed-api-reference
