### ISSUE TITLE
Publishing failing regardless of blueprint

### ISSUE THREAD

**Issue by andrewstevenson** [apiaryio/apiary-client#180]
Regardless of whats in apiary.apib publishing fails.

> warning: Overriding "Content-Type" header "text/plain" with "application/x-www-form-urlencoded" due to payload
Traceback (most recent call last):
        13: from /usr/local/bin/apiary:23:in `<main>'
        12: from /usr/local/bin/apiary:23:in `load'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/apiaryio-0.12.0/bin/apiary:5:in `<top (required)>'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
         6: from /usr/local/lib/ruby/gems/2.5.0/gems/apiaryio-0.12.0/lib/apiary/cli.rb:47:in `publish'
         5: from /usr/local/lib/ruby/gems/2.5.0/gems/apiaryio-0.12.0/lib/apiary/command/publish.rb:40:in `execute'
         4: from /usr/local/lib/ruby/gems/2.5.0/gems/apiaryio-0.12.0/lib/apiary/command/publish.rb:52:in `publish_on_apiary'
         3: from /usr/local/lib/ruby/gems/2.5.0/gems/apiaryio-0.12.0/lib/apiary/command/publish.rb:71:in `query_apiary'
         2: from /usr/local/lib/ruby/gems/2.5.0/gems/apiaryio-0.12.0/lib/apiary/command/publish.rb:81:in `rescue in query_apiary'
         1: from /usr/local/lib/ruby/gems/2.5.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
/usr/local/lib/ruby/gems/2.5.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse': 784: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//apiary-static.s3.amazonaws.com/assets/500.html"></iframe>
          </body>
        </html>'

**Comment by andrewstevenson** [comment]
wrong api name used

**Comment by kylef** [comment]
Even so, I think we should be emitting a clearer error message (like API Project doesn't exist, or permission problem etc). Showing a stacktrace and 500 error page isn't great.

I'll reopen so someone can look into resolving that.

**Comment by abtris** [comment]
We migrated into another platform. I will close ticket until we have similar issue again.
