### ISSUE TITLE
Bump rack version due to security advisory

### ISSUE THREAD

**Issue by aaronmarkey** [apiaryio/apiary-client#190]
A security advisory for the Ruby package `rack` was published on 2020-06-19.

Looks like `rack` versions  `2.1.4` and `2.2.3` have been patched, `apiary-client` should be bumped to account for this.

[Link to advisory](https://github.com/advisories/GHSA-j6w9-fv6q-3q52)

**Comment by anonoz** [comment]
Hey maintainers, how is this going?

**Comment by abtris** [comment]
Close by #192
