### ISSUE TITLE
Failed to open TCP connection to voight-kampfff-aws.apiary.services.com while executing apiary styleguide

### ISSUE THREAD

**Issue by rcarrascosps** [apiaryio/apiary-client#191]
While executing this:

apiary styleguide --add=marketv1.apib --functions=FunctionDefinitions.txt --rules=Rules.txt --full-report

I got:
Traceback (most recent call last):
        20: from D:/Ruby25-x64/bin/apiary:23:in `<main>'
        19: from D:/Ruby25-x64/bin/apiary:23:in `load'
        18: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/apiaryio-0.11.1/bin/apiary:5:in `<top (required)>'
        17: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        16: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        15: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        14: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        13: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/apiaryio-0.11.1/lib/apiary/cli.rb:60:in `styleguide'
        12: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/apiaryio-0.11.1/lib/apiary/command/styleguide.rb:42:in `execute'
        11: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/apiaryio-0.11.1/lib/apiary/command/styleguide.rb:113:in `validate'
        10: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/apiaryio-0.11.1/lib/apiary/command/styleguide.rb:194:in `call_resource'
         9: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2-x64-mingw32/lib/restclient/request.rb:52:in `execute'
         8: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2-x64-mingw32/lib/restclient/request.rb:145:in `execute'
         7: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2-x64-mingw32/lib/restclient/request.rb:715:in `transmit'
         6: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:909:in `start'
         5: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
         4: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:935:in `connect'
         3: from D:/Ruby25-x64/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
         2: from D:/Ruby25-x64/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
         1: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to voight-kampff-aws.apiary-services.com:443 (getaddrinfo: Host desconocido. ) (SocketError)

apiary version 0.11.1
Operative System: Windows.

This used to work some monts ago, but now it seems that server is gone.

Thank u

**Comment by rcarrascosps** [comment]
I've fixed it installing
apiary version 0.14.0

This issue may be closed.
best regards

rolando

**Comment by abtris** [comment]
ok, thanks
