### ISSUE TITLE
apiaryio/client in Docker Hub not up to date

### ISSUE THREAD

**Issue by bchew** [apiaryio/apiary-client#201]
Was looking to upgrade our usage of the `apiaryio/client` docker image to the latest but there does not seem to be anything >= `0.15.0` (latest seems to be `0.14.1` at https://hub.docker.com/r/apiaryio/client/tags?page=1&ordering=last_updated).

Could you please advise if there are plans to get the Docker Hub images up to date? Thanks.

**Comment by abtris** [comment]
hmm, process is [automated](https://github.com/apiaryio/apiary-client/blob/master/.github/workflows/release.yml) for release gem and docker. We will look into why missing that image there.

**Comment by abtris** [comment]
Issue should be resolved.
