### ISSUE TITLE
Preview is not working

### ISSUE THREAD

**Issue by eriknyk** [apiaryio/apiary-client#21]
Hi,
I'm trying execute preview:

$ apiary preview
/var/lib/gems/1.9.1/gems/apiaryio-0.0.8/lib/apiary/command/preview.rb:81: warning: Insecure world writable dir /home/erik/Applications in PATH, mode 040777
Couldn't get a file descriptor referring to the console

other try:

$ apiary preview --path ./apiary.apib
/var/lib/gems/1.9.1/gems/apiaryio-0.0.8/lib/apiary/command/preview.rb:81: warning: Insecure world writable dir /home/erik/Applications in PATH, mode 040777
Couldn't get a file descriptor referring to the console

same result,..

I have the file apiary.apib in the current directory that I'm executing apiary preview.

Please Help, Regards.

**Comment by josemota** [comment]
Any news on this? I'm facing the same issue and it's been almost an year since the last update with no resolution.

**Comment by Almad** [comment]
No, as it started working for me, but I forgot what I did, if anything :(

For me, it sounds like tty/pty problem, but it would be helpful to have more steps to reproduce. Eventually, could you please attach strace?

**Comment by alexpanov** [comment]
As stated by @milieu the ```--output``` option solves the issue.

The issue itself is related to the open command which works differently on Linux than it does on a Mac.
Here's the exact place that the error originates from: https://github.com/apiaryio/apiary-client/blob/f424908d513e20f414136b55729926f5dbdb9967/lib/apiary/command/preview.rb#L86

Other possible workaround would be to create a proper alias for ```open``` but I haven't figured out what that would be exactly.
