### ISSUE TITLE
Rack version too restrictive

### ISSUE THREAD

**Issue by matthewrudy** [apiaryio/apiary-client#23]
the apiaryio gem depends on `rack (~> 1.4.1)`

But rails 4.0.2 (specifically actionpack 4.0.2) depends on `rack (~> 1.5.2)`

As such I can't add `gem "apiaryio"` and get the latest version.

Would it be possible to loosen the rack constraint, perhaps `>= 1.4.0, < 1.6.0`?

**Comment by RudthMael** [comment]
Now it's not compatible with Rails 4.2:

```
Bundler could not find compatible versions for gem "rack":
    rails (= 4.2.3) ruby  depends on
          rack (~> 1.6) ruby

    apiaryio (~> 0.3.0) ruby depends on
      rack (< 1.6.0, >= 1.4.0) ruby
```
