### ISSUE TITLE
Preview shows old UI

### ISSUE THREAD

**Issue by rguerrettaz** [apiaryio/apiary-client#39]
I am using the beta version (3 column layout). There's no command to view my docs locally with this new layout.

**Comment by vincentriemer** [comment]
It's been a while since this was asked and there has been no change. Is there any possibility in escalating this?

**Comment by Almad** [comment]
It is, with this ;) We got preview out of door just before christmas, therefore this got closer to completion.

**Comment by Quagh** [comment]
Any ETA? :)

**Comment by inovakov** [comment]
+1

**Comment by Almad** [comment]
(bumped that internally, our hands should be more free after our meetup this week)

**Comment by Almad** [comment]
(work is starting, dev work coming in soon!)

**Comment by freaz** [comment]
The issue should be solved by [latest release](https://github.com/apiaryio/apiary-client/releases/tag/0.3.0).

Please let me know whether it solves your problem and in case you find any problems, let us know in separate issues
