### ISSUE TITLE
Ability to use `apiary.manifest` in preview

### ISSUE THREAD

**Issue by kevinjalbert** [apiaryio/apiary-client#44]
According to http://stackoverflow.com/questions/22643429/apiary-multiple-blueprint-file-into-one-api, it should be possible to split up an apiary API documentation over multiple files with the use of an `apary.manifest` file.

It would be ideal if the preview tool of the CLI supports this.

**Comment by tu1ly** [comment]
could lead to the confusing behaviour as apiary is not able to process manifest in both ways
closing for now

**Comment by kylef** [comment]
For users interested in this feature, I'd recommend checking out [Working with multiple blueprint files](https://gist.github.com/zdne/5f8295642af18aff27ec) and using Hercule within your workflow.

You can track adding proper support for multiple blueprints at API Blueprint:

- https://github.com/apiaryio/api-blueprint/issues/8
- https://github.com/apiaryio/api-blueprint/issues/20
