### ISSUE TITLE
Check apiary.apib files

### ISSUE THREAD

**Issue by jllucas** [apiaryio/apiary-client#48]
Hi,

doing "apiary publish --api-name XXXX" I realized that when apiary.apib is not well formed, the command doesn´t throws any error but the file is not loaded into "apiary.io".
Is there any way to check that apiary.apib files are well done (using apiaryio gem)?

Regards.

**Comment by honzajavorek** [comment]
The local check got removed. @jllucas please re-open this issue if you still experience problems with your blueprint. Thanks!
