### ISSUE TITLE
Ability to generate without the layout

### ISSUE THREAD

**Issue by balupton** [apiaryio/apiary-client#6]
Would be nice if we could get just the stuff in the left column.

Use case for this is to add an apiary blueprint plugin for [docpad](http://docpad.org) which we already use to generate our apiary blueprint file from CSON files (we render them to JSON and apply other abstractions).

Having this would allow us to use docpad to render the apiary blueprint as well.

**Comment by JackuB** [comment]
If you need different layout, we recommend using https://github.com/danielgtaylor/aglio for its customization possibilities.
