### ISSUE TITLE
Add validation as a stand-alone command.

### ISSUE THREAD

**Issue by chasingmaxwell** [apiaryio/apiary-client#67]
I understand that the blueprint is validated with redsnow before it's published. However, it would be nice to have the blueprint validated as a separate command so you could validate without publishing. This is especially useful if you're using apiaryio to put the blueprint under version control and want to validate your changes before committing.

**Comment by kylef** [comment]
Hi @chasingmaxwell, redsnow is a Ruby binding for the API Blueprint parser [snowcrash](https://github.com/apiaryio/snowcrash), it includes a command line tool you can use to validate your API Blueprint. The syntax is as follows:

```bash
$ snowcrash -l <blueprint>
```

If you're using [Sublime](https://github.com/apiaryio/api-blueprint-sublime-plugin) or [vim](https://github.com/kylef/apiblueprint.vim) be sure to check out the plugins which will allow you to validate your blueprint right from your editor.

**Comment by chasingmaxwell** [comment]
Excellent! Thanks for your help! I'm looking now at [Protagonist](https://github.com/apiaryio/protagonist) so we can easily integrate it with our gulp toolchain.
