### ISSUE TITLE
IP addresses to open in order to run Apiary inside of firewall

### ISSUE THREAD

**Issue by IGZnestorpina** [apiaryio/apiary-client#69]
Hi, I'm trying to run apiaryio client behind a corporate firewall.

Which ip addresses should be added in order to be able to run the client (I found [this 4](https://www.virustotal.com/en/domain/api.apiary.io/information/) for api.apiary.io, but just to make sure )

Also, which ports are called? Why [8080](https://github.com/apiaryio/apiary-client/blob/9125890103d7efe2ba91f9fce286e18ef1a4a282/lib/apiary/command/fetch.rb#L19) and not 80 or 443?

**Comment by Almad** [comment]
@IGZnestorpina We don't have any fixed IPs. The periodic lookup/upgrade is probably the best you can do. 

Port was created for debugging and [is actually unused](https://github.com/apiaryio/apiary-client/blob/9125890103d7efe2ba91f9fce286e18ef1a4a282/lib/apiary/command/fetch.rb#L59), 443 should go through—thanks for pointing that out //cc @abtris

**Comment by IGZnestorpina** [comment]
Thank you Almad. 

I hope they don't change too much :)

**Comment by Almad** [comment]
Not currently, but can't guarantee it :)
