### ISSUE TITLE
Blueprints won't load

### ISSUE THREAD

**Issue by jrep** [apiaryio/apiary-client#70]
Suddenly, some of my blueprints can't `apiary publish`, even though snowcrash and the app.apiary.io site like 'em just fine. I can't tell if this is a apiary-client issue or an app.apiary.io one.

Sample:

    > apiary publish --path _site/api/luna/config-visitor-prioritization-data/blueprint.apib --api-name akamaiopen2lunaconfigvisitorprioritizationdatadev
    Apiary service responded with an error: Blueprint you are trying to publish is not valid. Please validate with your snowcrash.

Yet:

    > snowcrash -l _site/api/luna/config-visitor-prioritization-data/blueprint.apib
    
    OK.

Versions:

```
> apiary version
0.2.4
> snowcrash -v
v0.16.1
```

Gist: https://gist.github.com/jrep/b462c73a1838cf99790d#file-blueprint-apib

**Comment by abtris** [comment]
Please, can you try with new 0.2.5 version?

**Comment by tu1ly** [comment]
is this still an issue ?
