### ISSUE TITLE
Attributes (Schema)

### ISSUE THREAD

**Issue by adammbalogh** [apiaryio/apiary-client#79]
Is it on purpose that attributes (schema) aren't formatted?

![example](http://i.imgur.com/upHSnjd.png)

**Comment by adammbalogh** [comment]
From another example, formatted code looks like (in the generated html file):

```html
<code class="language-javascript">{
        &#34;jsonrpc&#34;: &#34;2.0&#34;,
        &#34;id&#34;: 1,
        &#34;result&#34;: &#34;Hello Json Statham&#34;
}</code>
```

The "unformatted" content of Attributes tag looks like this:

```html
<code>{&#34;type&#34;:&#34;object&#34;,&#34;properties&#34;:{&#34;text&#34;:{&#34;...
```

There is no line break in the latter one...

**Comment by adammbalogh** [comment]
Do we have an update on this?

**Comment by kuba-kubula** [comment]
@adammbalogh The renderer at Apiary page does not change the schema in any way.
Even if it is a generated one.

Can you please post the piece of API Blueprint code, so I can try to work with that and look for possible solution to the (unfortunately) happening behavior? Thank you in advance.

**Comment by adammbalogh** [comment]
@kuba-kubula sure, I can.

Here is an original API Blueprint example: [Attributes](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/08.%20Attributes.md)

Apiary client (up-to-date) generates this:
![image](https://cloud.githubusercontent.com/assets/645053/8476598/28d653ba-20c3-11e5-9736-7a84f6184b43.png)

IMO the content of ```Schema : Response 200 (application/json)```should be formatted as well.

**Comment by honzajavorek** [comment]
Just to update you, fix of this issue is in the making and soon is going to be released!
