### ISSUE TITLE
Broken in windows, suggestions

### ISSUE THREAD

**Issue by Billiam** [apiaryio/apiary-client#8]
A few issues prevent this from working in windows:

 * Hardcoded path to /tmp/. Instead:

```
require `tmpdir'
path = "#{Dir.tmpdir}/path/to/file"
```
could be used.

  * Hardcoded browser open string `system("open file")`. This could be replaced with OS sniffing to support a switch to `start /b` instead, or a gem dependency to [launchy](http://www.copiousfreetime.org/projects/launchy/) along with `Launchy.open('tmpfile')`

Also ran into an issue trying to read from/launch the preview file before the write block completed, but that may be due to other changes I'd made.

Will try to put together a pull request later, but unsure how the --browser switch strings in the command line ought to be handled without making the user specify the full path via config or ENV variables.

**Comment by honzajavorek** [comment]
@Billiam is this still relevant? We [employed AppVeyor](https://ci.appveyor.com/project/Apiary/apiary-client/branch/master) to ensure our builds run on Windows.

**Comment by Billiam** [comment]
Partially. tmpdir has replaced the hardcoded /tmp, but preview still depends on exec 'open'. https://github.com/apiaryio/apiary-client/blob/539e921aa0da05733df843572aa79150d9c886bd/lib/apiary/command/preview.rb#L84

**Comment by honzajavorek** [comment]
@Billiam Good point. Leaving this open :disappointed:

**Comment by tu1ly** [comment]
https://github.com/apiaryio/apiary-client/pull/126 should solve `open` problem
