### ISSUE TITLE
apiary's docs don't seem to be up to date

### ISSUE THREAD

**Issue by jpillora** [apiaryio/apiary-client#82]
I'm looking into automatically publishing a new `.apib` on every change to our API, though http://docs.apiary.apiary.io/ seems to be out of sync with http://client.apiary.io/ (the problem I'm trying to solve :smile:). I know can read the the Ruby source and try to figure it out though my Ruby isn't very good and it would be nice to have some apiary meta docs

**Comment by honzajavorek** [comment]
@jpillora Thanks for pointing this out! Indeed, we should check these docs are in sync and up to date. Sorry for the inconvenience.

Is there anything specific you are grappling with so we could help you before we fix the docs?

**Comment by jpillora** [comment]
@honzajavorek  Awesome :) I just wanted to use this clients publish command, though instead of using the ruby tool, I wanted to use the HTTP API directly

**Comment by honzajavorek** [comment]
See [this](https://github.com/apiaryio/apiary-client/blob/master/lib/apiary/command/publish.rb#L62:L71) for the request. You basically need to perform a `POST` request to `https://api.apiary.io/blueprint/publish/<your-api-subdomain-in-apiary>` with following JSON data:

- code (blueprint code)
- messageToSave (commit message)

```json
{"code": "FORMAT...", "messageToSave": "fixed everything :baloon:"}
```

And following [headers](https://github.com/apiaryio/apiary-client/blob/master/lib/apiary/command/publish.rb#L22:L26):

- `Accept`: `text/html`
- `Content-Type`: `text/plain`
- `Authentication`: `Token <your-apiary-api-key>`

----------

**Warning:** It should work and if it doesn't, let us know please. However, please mind that the API is to be changed soon, probably re-worked from scratch. That's also why we're not completely eager to fully document it and support it - we'd like to make the overhaul first and then to promote it and give it to people with all the :tada: and :balloon: ;-)

**Comment by jpillora** [comment]
Ahh I seeee, thanks for the interim solution anyhow :)
