### ISSUE TITLE
Instance Validation

### ISSUE THREAD

**Issue by keithmgould** [apiaryio/apiary-client#83]
Hey Guys,

I'd like to look at specific response bodies, and validate them against blueprints. Very similar to whats going on here for json schema. 

https://robots.thoughtbot.com/validating-json-schemas-with-an-rspec-matcher

In particular I'd like to:

0. create a blueprint markdown file
0. create a request spec
0. compare the results in the response body to the markdown file.

Any help would be greatly appreciated!

**Comment by honzajavorek** [comment]
Hey @keithmgould, would https://github.com/apiaryio/dredd (http://dredd.api.sexy/) work for you? It's a tool for testing your API implementation against its description in API Blueprint.

**Comment by keithmgould** [comment]
Hey @honzajavorek, thank you. I don't think dredd would work, as I already have RSpec, and don't want to add the dredd server (node, etc...).

I would like to augment my request specs, which are already pretty far along, with blueprint validation.

something like: 
```
 expect(response.body).to be_valid_against("user")
```

and I'd write the custom matcher to check a blueprint directory for "user.md", or something...

**Comment by honzajavorek** [comment]
Hi, I noticed you're running a similar issue directly on the API Blueprint repo: https://github.com/apiaryio/api-blueprint/issues/206 Would you mind if I close this one? In case I have an idea how to help you, I'll go there. Also, `api-blueprint` issue generally gets larger audience, so for a general question of this sort it's probably a better place where to ask.
