### ISSUE TITLE
Apiary Preview Static Assets Access Denied

### ISSUE THREAD

**Issue by ScotterC** [apiaryio/apiary-client#84]
Hey guys,

on `apiary preview` everything starts up fine but all the static assets through fastly are denied. What's weird is that it seems to still dump the asset text but is returning a 403. See here: https://apiary.a.ssl.fastly.net/assets/css/docs.css

**Comment by XVincentX** [comment]
Hey,
we are aware of the problem and we're already working on a fix, that should be shipped in a not so far future. (matters of hours)

**Comment by ScotterC** [comment]
Awesome thanks

On Monday, June 8, 2015, Vincenzo Chianese <notifications@github.com> wrote:

> Hey,
> we are aware of the problem and we're already working on a fix, that
> should be shipped in a not so far future. (matters of hours)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apiaryio/apiary-client/issues/84#issuecomment-110137697>
> .
>


-- 
--
Scott Carleton
Artsicle, Co-Founder / CTO
scott@artsicle.com
C. 914 400 5085

**Comment by IRus** [comment]
#closed?

**Comment by XVincentX** [comment]
Unfortunately no. I lost the track of this one and I am not sure what's the status of this. I'll try to ping you back as soon as possible.

**Comment by IRus** [comment]
Afaik now preview endpoint is deprecated(returns empty "code" in response), so now apiary preview just constructs single html page with js and inline apib file.
