### ISSUE TITLE
CI configurations are inconsistent

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/apiary-client#88]
`appveyor.yml` doesn't contain `rake features` while `circle.yml` does.

**Comment by abtris** [comment]
Problem is in running `rake features` in Appveyor. This not work, problem find executable file, some windows path specific problems. We need someone with windows to solve this problem.

**Comment by honzajavorek** [comment]
Maybe @XVincentX could help?

**Comment by XVincentX** [comment]
I'll try to have a look.

**Comment by freaz** [comment]
I tried to fixed this. Unfortunately no luck. I tried it with RDP to Appveyor, but even I added all paths manually it did not work. I also tried to use relative paths to binaries but again it did not solve this problem.
