### ISSUE TITLE
Bug with unicode characters

### ISSUE THREAD

**Issue by zdne** [apiaryio/apiary-client#89]
> I've simply exported apiary key, then:

> apiary fetch --api-name=XXXX --output=apiary.apib

> then 

> apiary preview

> and got this error

> I've opened apiary.apib file but it its encoding was fine except I had some Polish characters in sample Json responses. After changing all national characters ą to a, ś to s etc. no error appeared connected to file encoding.

> When I had for example in sample json response:
> `"state": "śląskie",`
> I had this encoding error and after changing it into:
> `"state": "slaskie",`

**Comment by tu1ly** [comment]
can not reproduce - pls reopen if it is still an issue
