### ISSUE TITLE
APIARY_API_KEY accessibility

### ISSUE THREAD

**Issue by LilyJ** [apiaryio/apiary-client#95]
while testing the CLI I noticed that the APIARY_API_KEY must designame an account with WRITE access to the requested project -- even if the docs and blueprint are world-readable, as domain testingapiaryclitestingapiarycli

https://apiarysupport.zendesk.com/agent/tickets/184

**Comment by LilyJ** [comment]
ladislav [10:05 PM] 
@lily: this is not issue with apiary-client. We use some token for publish and fetch. I can discuss with @baggz if is possible with new api but in current api uses `apiary-client` is only one type rights and need write access.

**Comment by jrep** [comment]
I filed an [Apiary support ticket](https://urldefense.proofpoint.com/v2/url?u=https-3A__premium-2Dsupport.apiary.io_hc_requests_184&d=BQMFaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=zgpD9HQQTSRSToL2CV6KrxUs7TkKCVF12lkKi9ILvsA&m=bKtFqlGY_TKh8qmzwo1Yowk2_d3O-3BT7y-ndJweUx0&s=Lb5jMhFmrjQBhuqd1bLbwfciJrJ9TK5DeWnvpPzI-pg&e=) on this yesterday, oddly enough.

**Comment by jrep** [comment]
Also, related to [PR#87](https://github.com/apiaryio/apiary-client/pull/87), I'm working on making this a bit more usable.

**Comment by jrep** [comment]
I have made [apiary-client PR#96](https://github.com/apiaryio/apiary-client/pull/96), (the work mentioned just above) which among other things makes the tests independent of the user's APIARY_API_KEY.
